import type { Plugin } from 'vite'

import fs from 'node:fs/promises'
import path from 'node:path'

export interface KanjouOptions {
  localesDir?: string
  baseLocale?: string
  dtsPath?: string
}

const virtualModuleId = 'virtual:locales/'
const resolvedVirtualModuleId = '\0virtual:locales/'

export function kanjou({
  localesDir = './src/assets/locales',
  dtsPath = './src/generated',
  baseLocale = 'en',
}: KanjouOptions): Plugin {
  const resolvedDtsPath = path.resolve(dtsPath)
  const dtsDir = path.dirname(resolvedDtsPath)
  const virtualDtsPath = path.resolve(dtsDir, `${path.basename(dtsPath, '.d.ts')}.virtual.d.ts`)
  const baseLocalePath = path.resolve(localesDir, `${baseLocale}.json`)

  const generateDts = async () => {
    try {
      const content = await fs.readFile(baseLocalePath, 'utf-8')
      const messages: Record<string, string> = JSON.parse(content)

      const messagesFields = Object.entries(messages)
        .map(([key, value]) => `    "${key}": ${JSON.stringify(value)}`)
        .join('\n')

      const messagesDts = `/* eslint-disable */\n\n/* This file is autogenerated. Do not modify */

export {}

declare module '@kanjou/react' {
  export interface Messages {
${messagesFields}
  }
}
`
      await fs.writeFile(resolvedDtsPath, messagesDts, 'utf-8')

      const files = await fs.readdir(localesDir)

      const virtualModules = files
        .filter((f) => f.endsWith('.json'))
        .map((f) => {
          const locale = f.slice(0, -5)
          return `declare module 'virtual:locales/${locale}' {
  import type { Messages } from '@kanjou/react'
  const messages: Partial<Messages>
  export default messages
}`
        })
        .join('\n\n')

      const virtualDts = `/* eslint-disable */\n\n/* This file is autogenerated. Do not modify */\n\n${virtualModules}`
      await fs.writeFile(virtualDtsPath, virtualDts, 'utf-8')
    } catch (error) {
      console.error('d.ts generation error:', error)
    }
  }

  return {
    name: 'kanjou',
    async configResolved() {
      try {
        await fs.mkdir(dtsDir, { recursive: true })
      } catch (error) {
        console.error('Failed to create dts directory:', error)
      }
      await generateDts()
    },
    async handleHotUpdate({ file }) {
      if (file.startsWith(localesDir)) await generateDts()
    },
    resolveId(id) {
      if (id.startsWith(virtualModuleId)) {
        return resolvedVirtualModuleId + id.slice(virtualModuleId.length)
      }
    },
    async load(id) {
      if (!id.startsWith(resolvedVirtualModuleId)) return

      const locale = id.slice(resolvedVirtualModuleId.length)
      const filePath = path.resolve(localesDir, `${locale}.json`)

      this.addWatchFile(filePath)

      try {
        const fileContent = await fs.readFile(filePath, 'utf-8')
        const messages: Record<string, string> = JSON.parse(fileContent)

        const jsProperties = Object.entries(messages).map(([key, value]) => {
          if (value.includes('{')) {
            const escapedValue = value.replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
            const template = escapedValue.replace(/{(\w+)}/g, '${p.$1 ?? "{$1}"}')
            return `  "${key}": (p = {}) => \`${template}\``
          }
          return `  "${key}": ${JSON.stringify(value)}`
        })

        return `export default {\n${jsProperties.join(',\n')}\n}`
      } catch (error) {
        console.error(`Error loading locale ${locale}:`, error)
        return 'export default {}'
      }
    },
  }
}
